#include <cmath>
#include <cstdlib>
#include <iostream>

void proviamo4() {
  TFile *Laboratorio2 = new TFile("Laboratorio2.root", "READ");
  TCanvas *c1 = new TCanvas("c1", "Istogrammi fino ad ora1");
  TCanvas *c2 = new TCanvas("c2", "Istogrammi fino ad ora2");
  TCanvas *c3 = new TCanvas("c3", "Istogrammi fino ad ora3");
  TCanvas *c4 = new TCanvas("c4", "Istogrammi fino ad ora4");
  TCanvas *c5 = new TCanvas("c5", "Istogrammi fino ad ora5");
  TCanvas *c6 = new TCanvas("c6", "Istogrammi fino ad ora6");
  TCanvas *c7 = new TCanvas("c7", "Istogrammi fino ad ora7");
  TCanvas *c8 = new TCanvas("c8", "Istogrammi fino ad ora8");
  TCanvas *c9 = new TCanvas("c9", "Istogrammi fino ad ora9");
  TCanvas *c10 = new TCanvas("c10", "Istogrammi fino ad ora10");
  TCanvas *c11 = new TCanvas("c11", "Istogrammi fino ad ora11");
  TCanvas *c12 = new TCanvas("c12", "Istogrammi fino ad ora12");
  TCanvas *c15 = new TCanvas("c15", "Istogrammi fino ad ora15");
  TH1F *h1 = (TH1F *)Laboratorio2->Get("h1");
  TH1F *h2 = (TH1F *)Laboratorio2->Get("h2");
  TH1F *h3 = (TH1F *)Laboratorio2->Get("h3");
  TH1F *h4 = (TH1F *)Laboratorio2->Get("h4");
  TH1F *h5 = (TH1F *)Laboratorio2->Get("h5");
  TH1F *h6 = (TH1F *)Laboratorio2->Get("h6");
  TH1F *h7 = (TH1F *)Laboratorio2->Get("h7");
  TH1F *h8 = (TH1F *)Laboratorio2->Get("h8");
  TH1F *h9 = (TH1F *)Laboratorio2->Get("h9");
  TH1F *h10 = (TH1F *)Laboratorio2->Get("h10");
  TH1F *h11 = (TH1F *)Laboratorio2->Get("h11");
  TH1F *h12 = (TH1F *)Laboratorio2->Get("h12");
  TH1F *h15 = (TH1F *)Laboratorio2->Get("h15");
  c1->cd();
  h1->DrawCopy();
  c2->cd();
  h2->DrawCopy();
  c3->cd();
  h3->DrawCopy();
  c4->cd();
  h4->DrawCopy();
  c5->cd();
  h5->DrawCopy();
  c6->cd();
  h6->DrawCopy();
  c7->cd();
  h7->DrawCopy();
  c8->cd();
  h8->DrawCopy();
  c9->cd();
  h9->DrawCopy();
  c10->cd();
  h10->DrawCopy();
  c11->cd();
  h11->DrawCopy();
  c12->cd();
  h12->DrawCopy();
  c15->cd();
  h15->DrawCopy();
  /*h1->DrawCopy();
  h2->DrawCopy();
  h3->DrawCopy();
  h4->DrawCopy();
  h5->DrawCopy();
  h6->DrawCopy();
  h7->DrawCopy();
  h8->DrawCopy();
  h9->DrawCopy();
  h10->DrawCopy();
  h11->DrawCopy();
  h12->DrawCopy();
  h15->DrawCopy();*/
  TCanvas *c13 = new TCanvas("c13", "Istogrammi fino ad ora13");
  //TH1F *h13 = new TH1F("h13", "ok", 500, 0, 5);
  TCanvas *c14 = new TCanvas("c14", "Istogrammi fino ad ora14");
  //TH1F *h14 = new TH1F("h14", "ok", 500, 0, 5);
  h8->Add(h9,-1);
  h10->Add(h11,-1);
  c13->cd();
  h8->DrawCopy();
  c14->cd();
  h10->DrawCopy();
  Laboratorio2->Close();
}